services:
  enjambre:
    build: .
    container_name: kronos_enjambre
    restart: always
    volumes:
      - ./audit:/app/audit
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
